// Generated by Grafana k6 Studio (1.12.0) on 2026-04-08T08:51:21.332Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `da-DK,da;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://157.173.116.163:4200/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Origin: `http://157.173.116.163:4200`,
        Referer: `http://157.173.116.163:4200/`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `da-DK,da;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://157.173.116.163:8000/api/movies`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Origin: `http://157.173.116.163:4200`,
        Referer: `http://157.173.116.163:4200/`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `da-DK,da;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://157.173.116.163:8000/api/movies`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `*/*`,
        "Access-Control-Request-Method": `PUT`,
        "Access-Control-Request-Headers": `content-type`,
        Origin: `http://157.173.116.163:4200`,
        "Sec-Fetch-Mode": `cors`,
        Referer: `http://157.173.116.163:4200/`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `da-DK,da;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://157.173.116.163:8000/api/movies/1`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 204": (r) => r.status === 204 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        "Content-Type": `application/json`,
        Origin: `http://157.173.116.163:4200`,
        Referer: `http://157.173.116.163:4200/`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `da-DK,da;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://157.173.116.163:8000/api/movies/1`;
    resp = http.request(
      "PUT",
      url,
      `{"title":"star wars","id":1,"rating":9,"year":1,"description":""}`,
      params,
    );

    check(resp, { "status equals 204": (r) => r.status === 204 });
  });
  sleep(1);
}
