name: Build Backend Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # Checkout with full history (needed for versioning)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generate version
      - name: Get Custom Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"

      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GHCR - This is where we save to docker image we create
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push the docker image to the repository
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}/frontend:staging \
            -t ghcr.io/${{ github.repository }}/frontend:${{ steps.semver.outputs.version }} \
            ./Frontend

          docker build \
            -t ghcr.io/${{ github.repository }}/backend:staging \
            -t ghcr.io/${{ github.repository }}/backend:${{ steps.semver.outputs.version }} \
            ./Backend/Backend

          docker push ghcr.io/${{ github.repository }}/frontend --all-tags
          docker push ghcr.io/${{ github.repository }}/backend --all-tags

      # Create release notes
      - name: Create release notes
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver.outputs.version }}
          generateReleaseNotes: true

      # Deliver docker compose file to staging
      - name: Deliver docker compose file to staging
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: "docker-compose.yaml"
          target: dowa/

      # Run docker compose on the staging server
      - name: Run docker compose on the staging server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd dowa
            docker compose pull
            docker compose up -d
