- name: Install required tools
  run: |
    dotnet tool install -g dotnet-sonarscanner
    dotnet tool install -g dotnet-reportgenerator-globaltool

- name: Start Static Code Analysis
  run: |
    dotnet sonarscanner begin \
    /k:"${{ secrets.SONAR_PROJECT_KEY }}" \
    /d:sonar.host.url="${{ secrets.SONAR_URL }}" \
    /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
    /d:sonar.coverageReportPaths="coverage-report/SonarQube.xml" \
    /d:sonar.qualitygate.wait=true \
    /d:sonar.qualitygate.timeout=300

- name: Build
  run: dotnet build

- name: Run unit tests
  run: dotnet test --collect:"Xplat Code Coverage" --results-directory TestResults

- name: Generate Report
  run:
    reportgenerator \
    -reports:TestResults/**/coverage.cobertura.xml \
    -targetdir:coverage-report \
    -reporttypes:SonarQube

- name: Complete Static Code Analysis
  run: |
    dotnet sonarscanner end \
    /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
