name: Application version

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout med fuld historik
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Beregn versionen
      - name: Get Custom Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          # Indstillinger
          tag_prefix: "v"
          major_pattern: "(MAJOR)" # Hvad kigger den efter for major bumps
          minor_pattern: "(MINOR)" # Hvad kigger den efter for minor bumps
          version_format: "${major}.${minor}.${patch}"

      # 3. Brug versionsnummeret (f.eks. til at printe det eller bruge det i et build)
      - name: Display version
        run: echo "Den nye version er ${{ steps.semver.outputs.version }}"
